SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT) * p.price as SALES
FROM PRODUCT p
         JOIN OFFLINE_SALE o
              ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE